# Generated by Django 4.2.3 on 2024-06-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_cliente_cep_alter_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(max_length=120, unique=True, verbose_name='Cliente'),
        ),
    ]
