# Generated by Django 4.2.3 on 2024-06-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_cep_cliente_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('nome',), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='razao_social',
            new_name='nome',
        ),
    ]
