# Generated by Django 4.2.3 on 2024-06-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cnpj',
            new_name='telefone',
        ),
    ]
