# Generated by Django 4.2.3 on 2024-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_cnpj_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
