# Generated by Django 4.2.3 on 2024-08-07 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve conter somente número precedido do DDD e o 9.', regex='^\\d{2}9\\d{4}\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
