# Generated by Django 4.2.3 on 2024-06-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_ordemservico_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='data',
        ),
    ]
