# Generated by Django 4.2.3 on 2024-06-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_ordemservico_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoitem',
            name='tipo',
            field=models.CharField(choices=[('sl', 'Só lavar'), ('lp', 'Lavar e passar'), ('sp', 'Só passar'), ('na', 'Não se aplica')], default='na', max_length=2, verbose_name='Situação'),
            preserve_default=False,
        ),
    ]
