# Generated by Django 4.2.3 on 2024-06-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0008_alter_ordemservicoitem_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoitem',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='tipo',
            field=models.CharField(choices=[('sl', 'Só lavar'), ('lp', 'Lavar e passar'), ('sp', 'Só passar'), ('na', 'Não se aplica')], max_length=2, verbose_name='Tipo'),
        ),
    ]
