# Generated by Django 4.2.3 on 2024-06-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0009_ordemservicoitem_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='tipo',
            field=models.CharField(blank=True, choices=[('sl', 'Só lavar'), ('lp', 'Lavar e passar'), ('sp', 'Só passar'), ('na', 'Não se aplica')], max_length=2, null=True, verbose_name='Tipo'),
        ),
    ]
