# Generated by Django 4.2.3 on 2024-06-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0012_alter_ordemservicoitem_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='quantidade'),
        ),
    ]
