# Generated by Django 4.2.3 on 2024-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0015_remove_ordemservicoitem_proxima_visita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoitem',
            name='obs',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Observação'),
        ),
    ]
