# Generated by Django 4.2.3 on 2024-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0017_remove_ordemservicoitem_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
