# Generated by Django 4.2.3 on 2024-07-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0018_alter_ordemservicoitem_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('din', 'Dinheiro'), ('nao', 'Não pago')], default='pix', max_length=3, verbose_name='Pagamento'),
            preserve_default=False,
        ),
    ]
