# Generated by Django 4.2.3 on 2024-08-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0019_ordemservico_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_coleta',
            field=models.DateField(blank=True, null=True, verbose_name='Data de coleta'),
        ),
    ]
