# Generated by Django 4.2.3 on 2024-08-09 10:49

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_cliente_telefone'),
        ('servico', '0020_ordemservico_data_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_servicos', to='crm.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_coleta',
            field=models.DateField(default=datetime.date(1980, 1, 1), verbose_name='Data de coleta'),
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('999999'), max_digits=8, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='tipo',
            field=models.CharField(choices=[('sl', 'Só lavar'), ('lp', 'Lavar e passar'), ('sp', 'Só passar'), ('na', 'Não se aplica')], default='na', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('999999'), max_digits=8, verbose_name='valor'),
        ),
    ]
