# Generated by Django 4.2.3 on 2024-08-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0021_alter_ordemservico_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_coleta',
            field=models.DateField(blank=True, null=True, verbose_name='Data de coleta'),
        ),
    ]
