# Generated by Django 4.2.3 on 2024-08-09 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0022_alter_ordemservico_data_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_coleta',
            field=models.DateField(default=datetime.date(1980, 1, 1), verbose_name='Data de coleta'),
        ),
    ]
