# Generated by Django 4.2.3 on 2024-08-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0025_remove_servico_preco_only_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='preco_only_view_lavar',
            field=models.CharField(default='99999', max_length=6, verbose_name='Lavar'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_only_view_lavarpassar',
            field=models.CharField(default='99999', max_length=6, verbose_name='Lavar e Passar'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_only_view_passar',
            field=models.CharField(default='99999', max_length=6, verbose_name='Passar'),
        ),
    ]
