# Generated by Django 4.2.3 on 2024-08-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0026_alter_servico_preco_only_view_lavar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='deliver',
            field=models.BooleanField(default=False, verbose_name='Entrega'),
        ),
    ]
