# Generated by Django 4.2.3 on 2024-08-22 18:06

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0027_ordemservico_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_coleta',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Data de coleta'),
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='ordemservicoitem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='valor'),
        ),
    ]
