# Generated by Django 4.2.3 on 2024-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0028_alter_ordemservico_data_coleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='deliver',
            field=models.BooleanField(default=True, verbose_name='Entrega'),
        ),
    ]
