# Generated by Django 4.2.3 on 2024-08-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0029_alter_ordemservico_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='deliver',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, verbose_name='Entrega'),
        ),
    ]
