# Generated by Django 4.2.3 on 2024-08-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0030_alter_ordemservico_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='deliver',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Entrega'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_only_view_lavar',
            field=models.CharField(default='999', max_length=6, verbose_name='Lavar'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_only_view_lavarpassar',
            field=models.CharField(default='999', max_length=6, verbose_name='Lavar e Passar'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_only_view_passar',
            field=models.CharField(default='999', max_length=6, verbose_name='Passar'),
        ),
    ]
